# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Splash screen
exec-once = ~/Documents/scripts/splash.sh

exec-once = fcitx5

# Cursor
exec-once = hyprctl setcursor Breeze_Light 24

# KDE Connect
exec-once = kdeconnectd

# ARRPC
exec-once = npx arrpc


# Fix dock pinned apps not launching properly (https://github.com/end-4/dots-hyprland/issues/2200)
# This causes https://github.com/end-4/dots-hyprland/issues/2427
# exec-once = sleep 3.5 && hyprctl reload && sleep 0.5 && touch ~/.config/quickshell/ii/shell.qml
