# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/debug:enable_stdout_logs = 1
debug:enable_stdout_logs = 0
decoration:blur:xray = 1
decoration:blur:enabled = 1
decoration:blur:size = 3
decoration:blur:passes = 1

general {
	gaps_in = 7
	gaps_out = 10
	gaps_workspaces = 100
	border_size = 3

	col.active_border = rgb(09ddff) rgb(003ad0) 
	col.inactive_border = rgb(003ad0)
}
decoration {
    rounding_power = 3
    rounding = 0
	blur {
    enabled = true
		size = 3
		passes = 3
    xray = true
    special = false
    new_optimizations = true
    brightness = 1
    noise = 0
    contrast = 1
    vibrancy = 0.4
    vibrancy_darkness = 0.6
    popups = true
    popups_ignorealpha = 0.6
    input_methods = true
    input_methods_ignorealpha = 0.8

	}
	active_opacity = 0.85
	inactive_opacity = 0.80
	fullscreen_opacity = 1
}

