hl.config({ decoration = { blur = { size = 1 } } })
hl.config({ decoration = { blur = { passes = 3 } } })
hl.config({ decoration = { active_opacity = 1 } })
hl.config({ decoration = { inactive_opacity = 1 } })
hl.config({ general = { layout = "dwindle" } })
hl.config({ input = { kb_layout = "us" } })
hl.config({ input = { numlock_by_default = true } })
hl.config({ input = { repeat_delay = 250 } })
hl.config({ input = { repeat_rate = 35 } })
hl.config({ input = { follow_mouse = 1 } })
hl.config({ input = { touchpad = { natural_scroll = false } } })
hl.config({ input = { touchpad = { disable_while_typing = true } } })
hl.config({ input = { touchpad = { clickfinger_behavior = false } } })
hl.config({ input = { touchpad = { scroll_factor = 0.7 } } })
hl.config({ decoration = { rounding = 0 } })
hl.config({ decoration = { blur = { enabled = false } } })
hl.config({ general = { border_size = 4 } })
hl.config({ general = { gaps_in = 10 } })
hl.config({ general = { gaps_out = 15 } })
hl.config({ animations = { enabled = true } })
