-- DO NOT EDIT THIS FILE. IT IS MANAGED BY THE SHELL AND FOLLOWS STRICT RULES
-- In other words, I ain't writing a lua parser for this, so please be a good boi/girl/whatever
hl.config({general={layout="dwindle"}})
hl.animation({leaf="workspaces", enabled=true, speed=6, bezier="menu_decel", style="slide"})
hl.layer_rule({match={namespace="quickshell:dock"}, animation="slide bottom"})
