# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗
# Cool stuff 󰜥   

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """
$cmd_duration [](bold fg:#cdd6f4) $directory $git_branch $git_state[$git_status](bold fg:#f9e2af)
 $character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[$hostname  ](bold fg:blue)"
error_symbol = "[$hostname   ](bold fg:red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg: fg:#a6e3a1"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = "[](bold fg:#a6e3a1)[$symbol $branch(:$remote_branch)](fg:black bg:#a6e3a1)[](bold fg:#a6e3a1)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = "🚩"
ahead = ""
behind = ""
diverged = ""
untracked = ""
stashed = ""
modified = ""
staged = '[++\($count\)](green)'
renamed = "󰂮"
deleted = "🗑"

[username]
style_user = "bold bg:cyan fg:black"
style_root = "red bold"
format = "[](bold fg:cyan)[$user ]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[• $hostname](fg:black bg:cyan)[](fg:cyan)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = "%T"


[directory]
home_symbol = "  "
read_only = "  "
style = "bg:#64DCF0 fg:black"
truncation_length = 6
truncation_symbol = " ••/"
format = '[](bold fg:#64DCF0)[󰉋 $path]($style)[](bold fg:#64DCF0)'


[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[cmd_duration]
min_time = 0
format = '[](bold fg:yellow)[󰪢 $duration](bold bg:yellow fg:black)[](bold fg:yellow)'
